// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './styles/normalize.css'
;

import './styles/tailwind.css'
;

import './styles/global.css'
;

function App(props) {
  return React.createElement("div", {
              className: "text-red-500"
            }, "Hello ReScripters!");
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
